export enum Configuration {
    PORT='PORT',
    LOCAL='LOCAL',
    DOMAIN='DOMAIN',
    JWT_TOKEN_SECRET='JWT_TOKEN_SECRET',
    JWT_ACCESS_TOKEN_EXPIRATION_TIME='JWT_ACCESS_TOKEN_EXPIRATION_TIME',
    JWT_REFRESH_TOKEN_EXPIRATION_TIME='JWT_REFRESH_TOKEN_EXPIRATION_TIME',
    JWT_EMAIL_TOKEN_SECRET='JWT_EMAIL_TOKEN_SECRET',
    JWT_EMAIL_TOKEN_EXPIRATION_TIME='JWT_EMAIL_TOKEN_EXPIRATION_TIME',
    GOOGLE_EMAIL='GOOGLE_EMAIL',
    GOOGLE_CLIENT_ID='GOOGLE_CLIENT_ID',
    GOOGLE_SECRET='GOOGLE_SECRET',
    FACEBOOK_TOKEN='FACEBOOK_TOKEN'
};