export enum Configuracion {
    PORT='PORT',
    LOCAL='LOCAL',
    DOMAIN='DOMAIN',
    JWT_SECRETO='JWT_SECRETO',
    JWT_TIEMPO_EXPIRACION='JWT_TIEMPO_EXPIRACION',
    JWT_TIEMPO_EXPIRACION_CORREO='JWT_TIEMPO_EXPIRACION_CORREO',
    GOOGLE_EMAIL='GOOGLE_EMAIL',
    GOOGLE_CLIENT_ID='GOOGLE_CLIENT_ID',
    GOOGLE_SECRET='GOOGLE_SECRET',
    FACEBOOK_ID='FACEBOOK_ID',
    FACEBOOK_SECRET='FACEBOOK_SECRET'
};