export enum Configuration {
    PORT='PORT',
    LOCAL='LOCAL',
    DOMAIN='DOMAIN',
    JWT_SECRET='JWT_SECRET',
    JWT_TIME_EXPIRATION='JWT_TIME_EXPIRATION',
    JWT_TIME_EXPIRATION_EMAIL='JWT_TIME_EXPIRATION_EMAIL',
    GOOGLE_EMAIL='GOOGLE_EMAIL',
    GOOGLE_CLIENT_ID='GOOGLE_CLIENT_ID',
    GOOGLE_SECRET='GOOGLE_SECRET',
    FACEBOOK_ID='FACEBOOK_ID',
    FACEBOOK_SECRET='FACEBOOK_SECRET'
};